# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  _GCR_LOCATION: us-central1-docker.pkg.dev
  _IMAGE_REGISTRY: cw
  _IMAGE_NAME: local-llm
  _IMAGE_TAG: ${COMMIT_SHA:-latest}
steps:
  # Build and tag using commit sha
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        ".",
        "-t",
        "${_GCR_LOCATION}/$PROJECT_ID/${_IMAGE_REGISTRY}/${_IMAGE_NAME}:${_IMAGE_TAG}",
        "-f",
        "Dockerfile",
      ]
    dir: "."
  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_GCR_LOCATION}/$PROJECT_ID/${_IMAGE_REGISTRY}/${_IMAGE_NAME}:${_IMAGE_TAG}"]
images:
  - ${_GCR_LOCATION}/$PROJECT_ID/${_IMAGE_REGISTRY}/${_IMAGE_NAME}:${_IMAGE_TAG}
options:
  requestedVerifyOption: VERIFIED
  machineType: E2_HIGHCPU_32
  dynamicSubstitutions: true
