version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.handlers.RotatingFileHandler
    filename: /var/log/local-llm.log
  stdout:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: DEBUG
    handlers:
      - default
      - stdout
  uvicorn.access:
    level: DEBUG
    handlers:
      - default
root:
  level: DEBUG
  handlers:
    - default